# Generated by Django 4.0 on 2022-07-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='complain_pic'),
        ),
    ]
