# Generated by Django 4.0 on 2022-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0002_alter_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user_room_number',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
