# Generated by Django 3.2.15 on 2022-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_management', '0004_remove_complaint_user_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, upload_to='complain_pic'),
        ),
    ]
