# Generated by Django 3.2.15 on 2022-08-07 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_request', '0002_service_amenities_request_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Washing_machine_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField(max_length=12)),
                ('put_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('take_out_time', models.DateField(default=django.utils.timezone.now)),
                ('machine_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
