# Generated by Django 3.2.15 on 2022-08-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request', '0003_washing_machine_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washing_machine_request',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
