# Generated by Django 3.2.15 on 2022-08-07 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_request', '0004_alter_washing_machine_request_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washing_machine_request',
            name='take_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
