# Generated by Django 3.2.15 on 2022-08-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_management',
            name='check_in_date',
            field=models.DateField(null=True),
        ),
    ]
