# Generated by Django 3.2.15 on 2022-09-01 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room_management', '0002_alter_room_management_check_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_management',
            name='room_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
