# Generated by Django 3.2.15 on 2022-09-01 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room_management', '0004_alter_room_management_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_management',
            name='room_user',
        ),
        migrations.CreateModel(
            name='User_Room_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room_management.room_management')),
                ('room_user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
