# Generated by Django 3.2.15 on 2022-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0007_room_management_room_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_management',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
    ]
