# Generated by Django 4.0 on 2022-07-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_room_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
