# Generated by Django 4.0 on 2022-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile_user_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_room_number',
            field=models.IntegerField(default=0),
        ),
    ]
